apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: juniormoreira88/go-calculator:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: calculator
